# Generated by Django 3.1 on 2020-08-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200816_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
