# Generated by Django 3.1 on 2020-08-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200822_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/files'),
        ),
    ]
