# Generated by Django 3.1 on 2020-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20201121_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_description',
            field=models.TextField(default=''),
        ),
    ]
